# Lecture 4 - If, For

## Today's Key Takeaways

- If-elif-else statements
- For loops

In [1]:
# Import required libraries
import numpy as np
import pandas as pd
import scipy
from scipy import stats
import statsmodels.stats.multitest as smm
import matplotlib.pyplot as plt
from statsmodels.formula.api import ols
import seaborn as sns

pd.set_option('display.precision', 2)
pd.set_option('display.max_columns',10)

Let's start by importing our expression dataset

In [2]:
# importing the melanoma dataset
melanoma_log2 = pd.read_excel('~/LECTURE_MATERIALS/DataFiles/melanoma_zerosRemoved_log2transformed_2026.xlsx',index_col = 0)
melanoma_log2.head()

,Sample_geo_accession,Stage,cell type,sample_number,cell_line,...,ZYX,ZZEF1,ZZZ3,BP-21201H5.1,BP-2189O9.2
Sample Title,,,,,,,,,,,
FM_1,GSM2344965,primary melanocytes,normal melanocytes,1,FM,...,11.66,11.83,10.55,3.17,1.00
FM_2,GSM2344966,primary melanocytes,normal melanocytes,2,FM,...,11.63,11.54,11.06,2.81,2.00
FM_3,GSM2344967,primary melanocytes,normal melanocytes,3,FM,...,12.31,11.44,10.81,2.32,1.58
SK_MEL_28_1,GSM2344968,metastatic,melanoma cell line,4,SK_MEL_28,...,11.86,10.94,11.64,0.00,6.04
SK_MEL_28_2,GSM2344969,metastatic,melanoma cell line,5,SK_MEL_28,...,11.97,11.03,11.74,1.00,6.41

In [3]:
DEGresults = pd.read_csv('~/LECTURE_MATERIALS/DataFiles/DEGlog3resultsDF.csv',index_col = 0)
DEGresults.head()

        baseMean  log2FoldChange  lfcSE  stat    pvalue      padj
ABAT      376.14            3.14   0.78  4.04  5.30e-05  3.84e-04
ABCA1     107.95            4.76   0.76  6.29  3.10e-10  7.35e-09
ABCA13    286.18           -4.79   0.90 -5.30  1.13e-07  1.65e-06
ABCA4       5.83           -3.36   1.27 -2.65  8.04e-03  2.87e-02
ABCA8     190.51           -5.11   1.54 -3.32  8.90e-04  4.47e-03

#### Extracting some subsets of data

Let's extract some subsets of the expression data so that we have some examples to work with

In [4]:
# Extracting out only the gene expression dat from the normal samples and the metastatic samples
normExp = melanoma_log2.loc[melanoma_log2.Stage == 'primary melanocytes','A1BG':]
metastaticExp = melanoma_log2.loc[melanoma_log2.Stage == 'metastatic','A1BG':]

In [5]:
melanoma_log2.loc[:,'Stage']

Sample Title
FM_1            primary melanocytes
FM_2            primary melanocytes
FM_3            primary melanocytes
SK_MEL_28_1              metastatic
SK_MEL_28_2              metastatic
SK_MEL_28_3              metastatic
SK_MEL_147_1             metastatic
SK_MEL_147_2             metastatic
SK_MEL_147_3             metastatic
UACC_62_1                metastatic
UACC_62_2                metastatic
UACC_62_3                metastatic
Name: Stage, dtype: object

In [6]:
# calculates the overall variance df.var() and sorts it in descending order
overall_variance = melanoma_log2.loc[:,'A1BG':].var()
overall_variance.sort_values(inplace = True, ascending= False)
overall_variance.head()

# extract gene names for top 10 most variably expressed genes
topvarGens10 = overall_variance.index[:10].tolist()
print(topvarGens10)

['PMEL', 'TYRP1', 'AEBP1', 'GLUL', 'TYR', 'EEF1A2', 'CDC42EP1', 'A2M', 'SOD3', 'TGFBI']

## Conditionals: if statements

If statements execute a particular set of commands if a logical condition is met.

In [7]:
# Basic if statement
a = 3
b = 5
if b > a:
    print('the condition is true: b is greater than a')

the condition is true: b is greater than a

### elif and else
If-elif-else statements enable the execution of different commands based on whether different conditions are true.

In [8]:
x = 0
if x < 0:
    print('negative number')
elif x > 0:
    print('positive number')
else:
    print('zero')

zero

### Nesting multiple if statements

If you need to test multiple conditional statements, you can nest if statements within each other using `elif`.

In [9]:
# function with embeded if statements
def divisibleby(myNum):
    if myNum % 2 == 0:
        print('number is even')
        if myNum % 3 == 0:
          print('number is divisible by 3')

In [10]:
divisibleby(2)

number is even

In [12]:
divisibleby(3)

In [13]:
divisibleby(6)

number is even
number is divisible by 3

Contrast this against using an `and` conditional operator:

In [14]:
def divisiblebyAND(myNum):
    if myNum % 2 == 0 and myNum % 3 == 0:
        print('number is even')
        print('number is divisible by 3')

In [15]:
divisiblebyAND(2)

In [16]:
divisiblebyAND(3)

In [17]:
divisiblebyAND(6)

number is even
number is divisible by 3

For more information on if-elif-else conditionals, go [here](https://www.w3schools.com/python/python_conditions.asp) and [here](https://www.tutorialspoint.com/python/python_if_else.htm).

## Iteration: For-loops
For-loops enable iterating for a specific number of iterations.

The basic loop:

In [18]:
for loopingVar in range(1,5,1):
    print(loopingVar)

1
2
3
4

You can adjust the starting and stopping index of `range` by adjusting the input arguments. (More information about `range` can be found [here](https://www.w3schools.com/python/ref_func_range.asp)).

In [19]:
for loopingVar in range(2,10,2):
    print(loopingVar)

2
4
6
8

Note, that you can also use your `loopingVar` to iterate over the elements of a list or a `numpy` ndarray.

### Nesting multiple for-loops:

For-loops can also be nested. The innermost for-loop gets iterated first.

In [20]:
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

# a nested for loop
for x in adj:
    for y in fruits:
        print(x, y)

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry

### Nesting for-loops with conditional statements

More complex computations can be made by combining for-loops and if-statements.

Here's an example of how you can identify significant genes out of a list.

Note: we're also storing the significant values in new variables so that we can access them after the for-loop is complete.

In [21]:
pvals = [0.01,0.03,0.07,0.08,0.6,0.02,0.04,0.01] #a list of p-values generated from some other calculation.
sigIndex = [] # Creating an empty list to store the index values of which elements are significant
sigPvals = [] # Creating an empty list to store the p-values that are significant
for p in range(0,len(pvals),1):
  if pvals[p] < 0.05:
    print('significant pvalue:',pvals[p],', iteration number', p+1)
    sigPvals.append(pvals[p])
    sigIndex.append(p)

significant pvalue: 0.01 , iteration number 1
significant pvalue: 0.03 , iteration number 2
significant pvalue: 0.02 , iteration number 6
significant pvalue: 0.04 , iteration number 7
significant pvalue: 0.01 , iteration number 8

In [22]:
print(sigPvals)
print(sigIndex)

[0.01, 0.03, 0.02, 0.04, 0.01]
[0, 1, 5, 6, 7]

Here's another example where we would like to query the `DEGresults` data frame, which stores information about genes that are differentially expressed between metastatic and primary melanocytes of interest:

In [23]:
DEGresults.head()

        baseMean  log2FoldChange  lfcSE  stat    pvalue      padj
ABAT      376.14            3.14   0.78  4.04  5.30e-05  3.84e-04
ABCA1     107.95            4.76   0.76  6.29  3.10e-10  7.35e-09
ABCA13    286.18           -4.79   0.90 -5.30  1.13e-07  1.65e-06
ABCA4       5.83           -3.36   1.27 -2.65  8.04e-03  2.87e-02
ABCA8     190.51           -5.11   1.54 -3.32  8.90e-04  4.47e-03

In [24]:
DEGresults.loc[DEGresults.log2FoldChange > 10,:]

            baseMean  log2FoldChange  lfcSE   stat     pvalue       padj
AEBP1        4885.37           13.17   0.49  26.92  1.16e-159  1.16e-155
C1QTNF5       155.43           11.15   0.97  11.53   9.07e-31   1.83e-28
CD248          62.25           10.15   2.03   4.99   6.10e-07   7.48e-06
CDH1         6274.08           10.77   0.49  22.10  3.11e-108  7.82e-105
CYSLTR2      2411.19           12.46   0.69  18.09   4.02e-73   4.26e-70
DPP4         1349.07           10.07   0.99  10.15   3.28e-24   3.90e-22
EFS           276.47           12.30   1.10  11.18   4.89e-29   8.33e-27
GPX7           88.14           10.65   1.07   9.93   3.10e-23   3.44e-21
IP6K3         142.54           11.67   1.73   6.76   1.41e-11   4.13e-10
KDM5D         546.46           10.87   0.52  20.92   3.26e-97   6.55e-94
KIT          4479.17           11.34   1.02  11.17   5.52e-29   9.33e-27
NYNRIN        309.87           11.50   0.80  14.35   1.12e-46   5.50e-44
PNMAL2         82.17           10.87   1.17   9.31   1.25e-20   1.07e-18
RIPK3          74.62           10.73   1.24   8.65   4.99e-18   3.25e-16
SALL3          61.07           10.12   1.18   8.55   1.21e-17   7.58e-16
TCEAL7         96.18           10.45   1.08   9.65   4.89e-22   4.73e-20
TMEM132D      172.12           10.97   0.85  12.85   8.77e-38   2.99e-35
TMEM215        70.30           10.65   1.34   7.95   1.89e-15   9.41e-14
TNFRSF10D     465.86           10.41   0.75  13.83   1.72e-43   7.08e-41
TSPYL5        242.03           11.79   0.92  12.82   1.32e-37   4.23e-35
TXLNGY        198.84           10.55   0.73  14.40   5.11e-47   2.57e-44
TYRP1      201062.37           10.79   1.34   8.03   9.97e-16   5.10e-14

We further want to inspect the expression of these genes by each cell type

In [25]:
CellGroupbyDF = pd.concat([melanoma_log2.loc[:,'cell_line'],melanoma_log2.loc[:,'A1BG':]],axis = 1).groupby('cell_line').mean()
CellGroupbyDF

,A1BG,A2M,AAAS,AACS,AADAT,...,ZYX,ZZEF1,ZZZ3,BP-21201H5.1,BP-2189O9.2
cell_line,,,,,,,,,,,
FM,8.63,14.79,10.53,11.07,8.56,...,11.87,11.60,10.80,2.77,1.53
SK_MEL_147,8.00,2.13,10.94,11.09,10.34,...,13.07,11.14,12.11,5.13,5.23
SK_MEL_28,8.49,11.42,10.86,10.65,8.63,...,11.92,11.00,11.66,0.33,6.12
UACC_62,8.82,13.87,11.12,10.75,8.29,...,12.91,11.26,9.81,3.81,6.57

Let's combine a for-loop and if statement to extract a list of genes that that have a log2 fold change > 10 in the DEGresults and then print out what the cell line - averaged expression values for those genes are (if those genes are included in our `.describe` table).

In [26]:
for gene in DEGresults.index[:5]:
  print(gene)

ABAT
ABCA1
ABCA13
ABCA4
ABCA8

In [27]:
bigLFCgens = [] # Creating an empty list to store the p-values that are significant
for gene in DEGresults.index:
  if DEGresults.loc[gene,'log2FoldChange'] > 10:
    print('The significant gene', gene, ' has log2Fold change of:',DEGresults.loc[gene,'log2FoldChange'])
    bigLFCgens.append(gene)
    if gene in CellGroupbyDF.columns:
      print(CellGroupbyDF.loc[:,gene])

The significant gene AEBP1  has log2Fold change of: 13.169601677963884
cell_line
FM            14.06
SK_MEL_147     0.33
SK_MEL_28      1.30
UACC_62        1.06
Name: AEBP1, dtype: float64
The significant gene C1QTNF5  has log2Fold change of: 11.147386487774682
The significant gene CD248  has log2Fold change of: 10.147615967067184
The significant gene CDH1  has log2Fold change of: 10.768485061723686
cell_line
FM            14.46
SK_MEL_147     3.10
SK_MEL_28      4.58
UACC_62        3.35
Name: CDH1, dtype: float64
The significant gene CYSLTR2  has log2Fold change of: 12.456652044561096
The significant gene DPP4  has log2Fold change of: 10.074320407617524
The significant gene EFS  has log2Fold change of: 12.299824194348986
The significant gene GPX7  has log2Fold change of: 10.649895056878998
The significant gene IP6K3  has log2Fold change of: 11.665084902426566
The significant gene KDM5D  has log2Fold change of: 10.872945309122269
The significant gene KIT  has log2Fold change of: 11.341638254852306
The significant gene NYNRIN  has log2Fold change of: 11.501458795175015
The significant gene PNMAL2  has log2Fold change of: 10.87050821687933
The significant gene RIPK3  has log2Fold change of: 10.731293977113598
The significant gene SALL3  has log2Fold change of: 10.11968902486804
The significant gene TCEAL7  has log2Fold change of: 10.454030991971631
The significant gene TMEM132D  has log2Fold change of: 10.973448978317917
The significant gene TMEM215  has log2Fold change of: 10.64540355030212
The significant gene TNFRSF10D  has log2Fold change of: 10.410267335846068
The significant gene TSPYL5  has log2Fold change of: 11.786830994222578
The significant gene TXLNGY  has log2Fold change of: 10.548737999073063
The significant gene TYRP1  has log2Fold change of: 10.78897670442464
cell_line
FM            19.47
SK_MEL_147     4.25
SK_MEL_28     10.27
UACC_62        5.86
Name: TYRP1, dtype: float64

In [28]:
print(bigLFCgens)

['AEBP1', 'C1QTNF5', 'CD248', 'CDH1', 'CYSLTR2', 'DPP4', 'EFS', 'GPX7', 'IP6K3', 'KDM5D', 'KIT', 'NYNRIN', 'PNMAL2', 'RIPK3', 'SALL3', 'TCEAL7', 'TMEM132D', 'TMEM215', 'TNFRSF10D', 'TSPYL5', 'TXLNGY', 'TYRP1']

### <font color=brown>Hands on practice</font>

Extract the **top 3** most variably expressed genes from `melanoma_log2`. Use for loops to create a matrix that enumerates the **pairwise Euclidean distance** between the sample `FM_1` to each of the other samples. 

**Hints**:

1. The Euclidean distance between 2 samples that have the following expression values:

| Gene | Sample 1 | Sample 2 |
| --- | --- | --- |
| gene 1 | $x_1$ | $x_2$ |
| gene 2 | $y_1$ | $y_2$ |
| gene 3 | $z_1$ | $z_2$ |

can be calculated as:

$$
\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2 + (z_2 - z_1)^2}  
$$


2. You might want to convert a `numpy` array to a data frame as part of this question. If so, here's the syntax for that:

```
#Converting the numpy array "data" to the dataframe "df3"
df3 = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['col1', 'col2', 'col3'])
```

In [ ]:
#Reminders about existing variables that might be useful:
print(melanoma_log2.head())
print(topvarGens10)

In [ ]:
# Extracting top 3 variably expressed genes from melanoma_log2

In [1]:
# Setting up for loop for calculating distance

### <font color=brown>Hands on practice 2</font>
Can you extend this for loop so that you are calculating the pairwise distance between each sample and the other samples?

In [ ]:
# Modifying the for loop from above for distance for every pair of samples

### <font color=brown>Hands on practice 3</font>

Which pair of samples has the largest distance?

**Hint:** The syntax for `df.max()` and `df.idxmax()` as described [here](https://www.geeksforgeeks.org/find-maximum-values-position-in-columns-and-rows-of-a-dataframe-in-pandas/) might be helpful for figuring out what the pair with the maximum distance is. You might also want to try using the `stack()` method to help with finding the max. Reshaping data frames with `stack` and `melt` and other functions can be described [here](https://pandas.pydata.org/docs/user_guide/reshaping.html) and [here](https://www.geeksforgeeks.org/reshape-a-pandas-dataframe-using-stackunstack-and-melt-method/) .

In [ ]:
# Finding the pair of samples with the maximum distance

### <font color=blue>Optional Bonus hands on practice</font>

Extract the top 10 most variably expressed genes from melanoma_log2. Use for loops to calculate the pairwise Pearson correlation p-value between each of these 10 genes across the **metastatic samples**. Use an if-statement within the for-loop to report back which gene pairs are significantly correlated.

**Hints**:

1. The syntax to run a Pearson Correlation p-value is:

`corrP, pPearson = stats.pearsonr(normExp.iloc[0,:], normExp.iloc[1,:])`

where `pPearson` is the p-value associated with the pearson test.

2. Using an if-statement might help you to store information about the significant p-values, as in the example discussed above.

In [ ]:
#Reminders about existing variables that might be useful:
print(melanoma_log2.head())

In [ ]:
print(topvarGens10)

In [ ]:
# Extracting top 10 variably expressed genes from metastaticExp

In [4]:
#Setting up for loop for pairwise Pearson correlation p-value calculations and testing for significance

In [ ]:
# Create a data frame containing all the relevant variables

More information on for-loops can be found [here](http://www.yourownlinux.com/2016/12/python-loop-for-else-break-continue-statement.html).

### <font color=blue> Optional Bonus: Using Continue and Break
If we combine for- and while- loops with if-statements, we can perform more complex computations. Combining iteration with conditionals also enables the use of these additional operations:

- **continue** - skip an iteration
- **break** - end the loop

#### Continue

In [ ]:
# for loop with continue to print out only odd numbers
for myVar in range(1, 11):
    if myVar % 2 == 0 :
        #pass
        continue

    print('This number = ' + str(myVar))

#### Break

In [ ]:
# For loop with a break
for myVar in range(1, 11):
    if myVar > 5 :
        #pass
        break

    print('This number = ' + str(myVar))

### <font color=blue> Optional Bonus: For-else loops

If you add an `else` to for-loops, it will execute at the end, after the for-loop has finished iterating.

In [ ]:
for loopingVar in range(0,4,1):
    print(loopingVar)
else:
    print('done with the iterations')

#### The effect of Break on For-else loops

If the `break` statement is activated, then statements in the `else` blocks of for-else loops will not be executed.

In [ ]:
# for-else loop with break
def forElse(myNum):
    for myVar in range(1,6):
        if myVar == myNum:
            print( 'if statement is satisfied, breaking out of the loop')
            break
        else:
            print('This number = ' + str(myVar))
            myVar += 1
    else:
        print( 'break statement is not executed, printing else block')

In [ ]:
forElse(3)

In [ ]:
forElse(10)

#### <font color=brown>Hands on practice</font>

Create a function that uses a for-else loop to assess whether an input number is prime. Have this function print out the number's first two factors and then break if the input number is not prime. Otherwise, have the function print out that the input number is prime.

*Hint:* The `%` operator enables the calculation of remainders.

In [ ]:
def primeAssessment(myNum):
  for i in range(2,myNum): #to iterate on the factors of the number
    if myNum % i == 0:      #to determine the first factor
      j = myNum / i #to calculate the second factor
      print(myNum,'equals ', i ,'* ', j)
      break #to move to the next number, the #first FOR
  else:        # else part of the loop
    print(myNum, 'is a prime number')

In [ ]:
primeAssessment(15)

### <font color=blue> Optional Bonus: While-loops
Sometimes you might encounter a situation in which you don't know how many times you need to iterate, but you do need to iterate a command until a condition is met. While-loops are suitable for executing this kind of function.

The basic while-loop:

In [ ]:
targetNum = 5
countVar = 1
while countVar <= targetNum:
    print(countVar)
    #countVar = countVar + 1
    countVar += 1

##### <font color=brown>Hands on practice</font>

Use the while loop to iterate through the genes in order of descending variance whilst the variance of that gene across all samples in `melanoma_log2` is greater than 25. For each iteration's corresponding gene, calculate the difference in the mean log2 expression values between the metastatic vs. the normal samples for that gene.

In [ ]:
#Reminder of useful variables
print(overall_variance.head())
print(overall_variance[0])
print(overall_variance.index[0])

print(normExp['PMEL'].mean())
print(normExp.head())
metastaticExp.head()

In [ ]:
# Code for while loop
countIX = 0
StageMeanDiff = []
while overall_variance[countIX] > 25:
  mdiff = metastaticExp[overall_variance.index[countIX]].mean() - normExp[overall_variance.index[countIX]].mean()
  StageMeanDiff.append(mdiff)
  countIX += 1

print(StageMeanDiff)

In [ ]:
melStageMeanDiff[overall_variance > 25]

More information on while-loops can be found [here](http://www.yourownlinux.com/2016/12/python-while-else-loop-break-continue-statement.html).

In [ ]:
# While loop with a break
myNum = 11
myVar = 1
while myVar < myNum :
    print('This is iteration #' + str(myVar))
    if myVar == 6 :
            #pass
            print('This is the last iteration and we stop here.')
            break
    myVar += 1

In [ ]:
# while loop with continue
myNum = 15
myVar = 1
while myVar < myNum :
    if myVar % 2 != 0 :
        myVar += 1
        continue

    print('This number = ' + str(myVar))
    myVar += 1

#### <font color=blue> Optional Bonus: While-else loops

If you add an `else` to while-loops, it will execute at the end, after the while-loop has finished iterating.

In [ ]:
i = 1
while i < 6:
    print(i)
    i += 1
else:
    print("i is no longer less than 6")

In [ ]:
# while-else loop with break
def whileElse(myNum):
    myVar = 1
    while myVar <= 10 :
        if myVar == myNum :
            print('if statement satistifed, breaking out of the loop')
            break

        print('This number = ' + str(myVar))
        myVar += 1

    else:
        print('break statement is not executed, printing "else" block')

In [ ]:
whileElse(5)

In [ ]:
whileElse(12)