# Practice Problem Set 3 - KEY

Please note that the code here is just one way of getting the correct answer. Often, there are different ways to get to the same answer. If you have questions, please let us know.

In [1]:
# Makes it so any variable or statement on it's own line gets printed w/o print()
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
# Import required libraries
import numpy as np
import pandas as pd
import scipy

In [3]:
# Setting some pandas preferences
pd.set_option('display.precision', 2)
pd.set_option('display.max_columns',10)

### Import the raw count data:
Start by importing the melanoma_CountsRaw spreadsheet from last week and index by the sampleID column.

In [4]:
# Import comma-seperated data from a text file
df = pd.read_csv('melanoma_CountsRaw.csv')
df

,Sample Title,Sample_geo_accession,Stage,cell type,sample_number,...,BP-2171C21.4,BP-2171C21.5,BP-2171C21.6,BP-2189O9.2,YR211F11.2
0,FM_1,GSM2344965,primary melanocytes,normal melanocytes,1,...,0,0,6,2,0
1,FM_2,GSM2344966,primary melanocytes,normal melanocytes,2,...,0,0,0,4,0
2,FM_3,GSM2344967,primary melanocytes,normal melanocytes,3,...,1,0,6,3,1
3,SK_MEL_28_1,GSM2344968,metastatic,melanoma cell line,4,...,3,0,15,66,0
4,SK_MEL_28_2,GSM2344969,metastatic,melanoma cell line,5,...,0,2,21,85,0
5,SK_MEL_28_3,GSM2344970,metastatic,melanoma cell line,6,...,0,0,14,60,1
6,SK_MEL_147_1,GSM2344971,metastatic,melanoma cell line,7,...,0,0,5,37,0
7,SK_MEL_147_2,GSM2344972,metastatic,melanoma cell line,8,...,0,0,6,34,2
8,SK_MEL_147_3,GSM2344973,metastatic,melanoma cell line,9,...,0,0,9,42,0
9,UACC_62_1,GSM2344974,metastatic,melanoma cell line,10,...,0,0,46,123,0
10,UACC_62_2,GSM2344975,metastatic,melanoma cell line,11,...,0,0,25,79,1
11,UACC_62_3,GSM2344976,metastatic,melanoma cell line,12,...,4,0,22,89,0

### Data Manipulation Practice:
Perform the following manipulations of the metadata.

1) Show a preview of the first few rows of the data frame.

In [5]:
df.head()

,Sample Title,Sample_geo_accession,Stage,cell type,sample_number,...,BP-2171C21.4,BP-2171C21.5,BP-2171C21.6,BP-2189O9.2,YR211F11.2
0,FM_1,GSM2344965,primary melanocytes,normal melanocytes,1,...,0,0,6,2,0
1,FM_2,GSM2344966,primary melanocytes,normal melanocytes,2,...,0,0,0,4,0
2,FM_3,GSM2344967,primary melanocytes,normal melanocytes,3,...,1,0,6,3,1
3,SK_MEL_28_1,GSM2344968,metastatic,melanoma cell line,4,...,3,0,15,66,0
4,SK_MEL_28_2,GSM2344969,metastatic,melanoma cell line,5,...,0,2,21,85,0

2) Determine the number of rows and columns in the data frame.

In [6]:
df.shape

(12, 35244)

3. Create a `meta` data frame that only contains the metadata

In [7]:
meta = df.loc[:,:'cell_line']
meta.head()

,Sample Title,Sample_geo_accession,Stage,cell type,sample_number,cell_line
0,FM_1,GSM2344965,primary melanocytes,normal melanocytes,1,FM
1,FM_2,GSM2344966,primary melanocytes,normal melanocytes,2,FM
2,FM_3,GSM2344967,primary melanocytes,normal melanocytes,3,FM
3,SK_MEL_28_1,GSM2344968,metastatic,melanoma cell line,4,SK_MEL_28
4,SK_MEL_28_2,GSM2344969,metastatic,melanoma cell line,5,SK_MEL_28

4) Add an extra column to the data frame meta that shows the gene counts for A2MP1.

In [8]:
A2MP1 = df.A2MP1
A2MP1 = np.array(A2MP1)
meta['A2MP1 Counts']=A2MP1
meta

,Sample Title,Sample_geo_accession,Stage,cell type,sample_number,cell_line,A2MP1 Counts
0,FM_1,GSM2344965,primary melanocytes,normal melanocytes,1,FM,21
1,FM_2,GSM2344966,primary melanocytes,normal melanocytes,2,FM,7
2,FM_3,GSM2344967,primary melanocytes,normal melanocytes,3,FM,34
3,SK_MEL_28_1,GSM2344968,metastatic,melanoma cell line,4,SK_MEL_28,0
4,SK_MEL_28_2,GSM2344969,metastatic,melanoma cell line,5,SK_MEL_28,6
5,SK_MEL_28_3,GSM2344970,metastatic,melanoma cell line,6,SK_MEL_28,3
6,SK_MEL_147_1,GSM2344971,metastatic,melanoma cell line,7,SK_MEL_147,0
7,SK_MEL_147_2,GSM2344972,metastatic,melanoma cell line,8,SK_MEL_147,0
8,SK_MEL_147_3,GSM2344973,metastatic,melanoma cell line,9,SK_MEL_147,0
9,UACC_62_1,GSM2344974,metastatic,melanoma cell line,10,UACC_62,13
10,UACC_62_2,GSM2344975,metastatic,melanoma cell line,11,UACC_62,3
11,UACC_62_3,GSM2344976,metastatic,melanoma cell line,12,UACC_62,3

5) Create a variable that contains the sample accession number information for all of the samples and then remove the first three characters from each accession number.

In [9]:
accession = meta.Sample_geo_accession
accession = accession.str[3:]
print(accession)

0     2344965
1     2344966
2     2344967
3     2344968
4     2344969
5     2344970
6     2344971
7     2344972
8     2344973
9     2344974
10    2344975
11    2344976
Name: Sample_geo_accession, dtype: object

6) Make a data frame of boolean values showing where there are read counts greater than 1,000.

In [10]:
df_high = df.loc[:,'A1BG':] >1000
df_high

,A1BG,A1CF,A2M,A2ML1,A2MP1,...,BP-2171C21.4,BP-2171C21.5,BP-2171C21.6,BP-2189O9.2,YR211F11.2
0,False,False,True,False,False,...,False,False,False,False,False
1,False,False,True,False,False,...,False,False,False,False,False
2,False,False,True,False,False,...,False,False,False,False,False
3,False,False,True,False,False,...,False,False,False,False,False
4,False,False,True,False,False,...,False,False,False,False,False
5,False,False,True,False,False,...,False,False,False,False,False
6,False,False,False,False,False,...,False,False,False,False,False
7,False,False,False,False,False,...,False,False,False,False,False
8,False,False,False,False,False,...,False,False,False,False,False
9,False,False,True,False,False,...,False,False,False,False,False
10,False,False,True,False,False,...,False,False,False,False,False
11,False,False,True,False,False,...,False,False,False,False,False

7) Add together all of the columns to get the total number of samples with counts >1,000 and then calculate the summary parameters to get a sense of the distribution.

In [11]:
highsum = df_high.sum()
print(highsum.head())
print(highsum.describe())

A1BG     0
A1CF     0
A2M      9
A2ML1    0
A2MP1    0
dtype: int64
count    35238.00
mean         2.24
std          4.27
min          0.00
25%          0.00
50%          0.00
75%          1.00
max         12.00
dtype: float64

8) Make a list of genes that have reads for all 12 samples and calculate how many genes we are keeping.

In [12]:
keep = highsum > 11
print(keep.head())
print(np.sum(keep))

A1BG     False
A1CF     False
A2M      False
A2ML1    False
A2MP1    False
dtype: bool
4180

9) Remove all of the genes from df that don't have >1,000 reads for all 12 samples and dimensions of the data frame before and after removal.

In [13]:
exp = df.loc[:,'A1BG':]
exp_low_removed = exp.loc[:,keep]
print(exp_low_removed.head())
print(exp.shape)
print(exp_low_removed.shape)

   AAAS  AACS  AAGAB  AAMP  AAR2  ...  ZRANB2  ZSWIM8  ZYG11B   ZYX  ZZEF1
0  1486  1770   1417  2588  2398  ...    1274    5456    1693  3230   3639
1  1371  2064   1700  2502  1917  ...    1023    3292    1681  3171   2979
2  1589  2731   1328  2878  1899  ...    1486    4432    1345  5070   2770
3  1734  1667   1443  6952  1938  ...    3162    2520    1711  3720   1967
4  1919  1710   1656  7694  2135  ...    4607    2710    1661  4002   2096

[5 rows x 4180 columns]
(12, 35238)
(12, 4180)

10) Now log10 transform the df_low_removed data frame.

In [14]:
exp_low_removed_log10 = np.log10(exp_low_removed)
exp_low_removed_log10.head()

   AAAS  AACS  AAGAB  AAMP  AAR2  ...  ZRANB2  ZSWIM8  ZYG11B   ZYX  ZZEF1
0  3.17  3.25   3.15  3.41  3.38  ...    3.11    3.74    3.23  3.51   3.56
1  3.14  3.31   3.23  3.40  3.28  ...    3.01    3.52    3.23  3.50   3.47
2  3.20  3.44   3.12  3.46  3.28  ...    3.17    3.65    3.13  3.71   3.44
3  3.24  3.22   3.16  3.84  3.29  ...    3.50    3.40    3.23  3.57   3.29
4  3.28  3.23   3.22  3.89  3.33  ...    3.66    3.43    3.22  3.60   3.32

[5 rows x 4180 columns]

11) Calculate the minimum, maximum, mean, and standard deviation for the first 5 genes.

In [16]:
exp_low_removed_log10.iloc[:,:5].aggregate(['min','max','mean','std'])

      AAAS  AACS  AAGAB  AAMP  AAR2
min   3.14  3.16   3.12  3.40  3.19
max   3.39  3.44   3.47  3.89  3.45
mean  3.27  3.28   3.25  3.67  3.32
std   0.07  0.08   0.12  0.17  0.07

12) Join the meta data frame with the df_low_removed_log10 data frame, determine the dimensions, and preview the first few rows.

In [17]:
meta_log10 = pd.concat([meta,exp_low_removed_log10],axis = 1)
meta_log10.shape
meta_log10.head()

(12, 4187)

,Sample Title,Sample_geo_accession,Stage,cell type,sample_number,...,ZRANB2,ZSWIM8,ZYG11B,ZYX,ZZEF1
0,FM_1,GSM2344965,primary melanocytes,normal melanocytes,1,...,3.11,3.74,3.23,3.51,3.56
1,FM_2,GSM2344966,primary melanocytes,normal melanocytes,2,...,3.01,3.52,3.23,3.50,3.47
2,FM_3,GSM2344967,primary melanocytes,normal melanocytes,3,...,3.17,3.65,3.13,3.71,3.44
3,SK_MEL_28_1,GSM2344968,metastatic,melanoma cell line,4,...,3.50,3.40,3.23,3.57,3.29
4,SK_MEL_28_2,GSM2344969,metastatic,melanoma cell line,5,...,3.66,3.43,3.22,3.60,3.32

#### Import the data frame we made in class on Monday.
Import `melanoma_zerosRemoved_log2transformed_2025.xlsx`.

In [18]:
melanoma_log2 = pd.read_excel('melanoma_zerosRemoved_log2transformed_2025.xlsx',index_col = 0)
melanoma_log2.head()

,Sample_geo_accession,Stage,cell type,sample_number,cell_line,...,ZYX,ZZEF1,ZZZ3,BP-21201H5.1,BP-2189O9.2
Sample Title,,,,,,,,,,,
FM_1,GSM2344965,primary melanocytes,normal melanocytes,1,FM,...,11.66,11.83,10.55,3.17,1.00
FM_2,GSM2344966,primary melanocytes,normal melanocytes,2,FM,...,11.63,11.54,11.06,2.81,2.00
FM_3,GSM2344967,primary melanocytes,normal melanocytes,3,FM,...,12.31,11.44,10.81,2.32,1.58
SK_MEL_28_1,GSM2344968,metastatic,melanoma cell line,4,SK_MEL_28,...,11.86,10.94,11.64,0.00,6.04
SK_MEL_28_2,GSM2344969,metastatic,melanoma cell line,5,SK_MEL_28,...,11.97,11.03,11.74,1.00,6.41

13) Calculate the summary parameters (using .describe) for the first 8 genes in melanoma_log2.

In [19]:
melanoma_log2.iloc[:,5:13].describe()

        A1BG    A2M   AAAS   AACS  AADAT  AAED1  AAGAB   AAK1
count  12.00  12.00  12.00  12.00  12.00  12.00  12.00  12.00
mean    8.49  10.55  10.86  10.89   8.95   9.47  10.81  11.09
std     0.46   5.26   0.25   0.28   0.88   0.47   0.40   0.62
min     7.81   1.58  10.42  10.51   7.94   8.89  10.38   9.91
25%     8.27   9.23  10.73  10.68   8.47   9.16  10.60  10.95
50%     8.44  12.41  10.92  10.89   8.60   9.32  10.68  11.38
75%     8.62  14.37  10.98  11.06   9.13   9.72  10.90  11.48
max     9.56  15.54  11.27  11.42  10.56  10.31  11.52  11.56

14) Let's say we want to find the genes that have the highest average counts across conditions. Calculate the overall average, sort this series, and select the top 5 genes with the highest average counts.

In [21]:
overall_average = melanoma_log2.iloc[:,5:].mean()

overall_average.sort_values(inplace = True, ascending = False)

topmean = overall_average[:5]
print(topmean)
type(topmean)

EEF1A1    18.22
VIM       17.42
MT-CO1    17.23
ACTB      17.04
GAPDH     16.97
dtype: float64

pandas.core.series.Series

15) Make a subtable called topmeantable to look at what the actual expression count values were for these genes.

In [22]:
topmeantable = melanoma_log2.loc[:,topmean.index]
topmeantable

              EEF1A1    VIM  MT-CO1   ACTB  GAPDH
Sample Title
FM_1           18.12  17.33   19.28  16.55  15.15
FM_2           18.29  17.35   18.00  17.11  15.65
FM_3           18.44  17.85   19.18  16.86  15.88
SK_MEL_28_1    18.48  17.07   17.07  17.15  17.11
SK_MEL_28_2    18.53  17.16   17.31  17.32  17.18
SK_MEL_28_3    18.59  17.09   17.92  17.15  17.26
SK_MEL_147_1   18.20  17.88   15.77  17.27  17.06
SK_MEL_147_2   18.15  17.88   15.84  17.32  17.14
SK_MEL_147_3   18.24  17.61   15.69  16.98  16.99
UACC_62_1      17.96  17.16   17.66  16.80  18.05
UACC_62_2      17.91  17.41   16.44  17.07  18.18
UACC_62_3      17.77  17.20   16.62  16.94  17.97

16) Next, group melanoma_log2 by "cell line" and calculate the group-by mean.

In [25]:
mel_by_cell = melanoma_log2.loc[:,'cell_line':].groupby('cell_line')
mel_by_cell_mean = mel_by_cell.mean()
mel_by_cell_mean

,A1BG,A2M,AAAS,AACS,AADAT,...,ZYX,ZZEF1,ZZZ3,BP-21201H5.1,BP-2189O9.2
cell_line,,,,,,,,,,,
FM,8.63,14.79,10.53,11.07,8.56,...,11.87,11.60,10.80,2.77,1.53
SK_MEL_147,8.00,2.13,10.94,11.09,10.34,...,13.07,11.14,12.11,5.13,5.23
SK_MEL_28,8.49,11.42,10.86,10.65,8.63,...,11.92,11.00,11.66,0.33,6.12
UACC_62,8.82,13.87,11.12,10.75,8.29,...,12.91,11.26,9.81,3.81,6.57

17) Lastly, find the median, variance, and standard deviation of the first 10 genes.

In [26]:
mel_by_cell_mean.iloc[:,1:11].aggregate(['median','var','std'])

          A2M   AAAS   AACS  AADAT  AAED1  AAGAB   AAK1  AAMDC   AAMP   AAR2
median  12.64  10.90  10.91   8.59   9.41  10.64  11.40   7.70  12.30  10.99
var     33.54   0.06   0.05   0.87   0.23   0.18   0.45   0.98   0.38   0.03
std      5.79   0.25   0.22   0.93   0.48   0.43   0.67   0.99   0.61   0.17